title: Hemma
views:
  # Main View
  - title: Översikt
    # Icon used for the tab
    icon: mdi:home-modern
    # ID - must be unique
    id: Oversikt
    # Cards to show in the view
    cards:
      # Presence card
      - id: presence
        type: glance
        entities:
          - entity: device_tracker.9c5cf9c2bc62
            name: Johan
          - entity: device_tracker.androidce7ba79f584b865d
            name: Caroline
      # Weather forecast cards

  # Ligth Control View
  - title: Belysning
    # Icon used for the tab
    icon: mdi:lightbulb-on-outline
    # ID, must be unique
    id: Belysning
    # Cards to show in the view
    cards:
      # Bedroom
      - id: Sovrummet
        type: horizontal-stack
        cards:
          - id: sovrummet-fonster
            type: glance
            entities:
              - entity: switch.sovrum_fonster_switch
                name: Fönstret
          - type: light
            id: sovrummet-sanggavel
            entity: light.bed_headboard

      # Livingroom
      - id: Vardagsrummet
        type: glance
        title: Vardagsrummet
        entities:
          - entity: switch.vardagsrum_fonster_switch
            name: Fönstret

      # Kitchen
      - id: Koket
        type: glance
        title: Köket
        entities:
          - entity: light.koket_taklampa
            name: Taklampa
          - entity: light.koket_bordet
            name: Bordet
          - entity: switch.kok_fonster_switch
            name: Fönstret

      # Hallway
      - id: Hallen
        type: entities
        title: Hallen
        show_header_toggle: false
        entities:
          - entity: light.korridoren
            name: Korridoren
          - entity: light.entren
            name: Entren

  # TV Control View
  # Maintenance View
